FROM node:20-alpine

WORKDIR /app

# 先裝依賴
COPY package*.json ./
RUN npm install

# Build 前端
COPY . .
ARG VITE_GIPHY_API_KEY
ARG VITE_TENOR_API_KEY
ARG VITE_OPENAI_API_KEY
ARG VITE_GEMINI_API_KEY

ENV VITE_GIPHY_API_KEY=$VITE_GIPHY_API_KEY
ENV VITE_TENOR_API_KEY=$VITE_TENOR_API_KEY
ENV VITE_OPENAI_API_KEY=$VITE_OPENAI_API_KEY
ENV VITE_GEMINI_API_KEY=$VITE_GEMINI_API_KEY

RUN npm run build

# 啟動後端 server.js
EXPOSE 8080
CMD ["node", "server.js"]
